spring.application.name=bookmyshow

server.port=8080

logging.level.org.springframework=info


#  DATA SOURCE

# configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyshow
#spring.datasource.url=jdbc:postgresql://dpg-cu67hplds78s73ahfa70-a.singapore-postgres.render.com:5432/bookmoviedb_sho1
spring.datasource.username=postgres
#spring.datasource.username=bookmoviedb_sho1_user
spring.datasource.password=devmanish123
#spring.datasource.password=t7YWK41KqNSgxVsuXqW3I6CzvBgWbebN
spring.datasource.driver-class-name=org.postgresql.Driver
# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.show-sql=true
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=update

# Naming strategy
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#
## Allows Hibernate to generate SQL optimized for a particular DBMS
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

